import{a as h,S as F,i as n}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="44009462-82273816cd5912ea13bf70156",p="https://pixabay.com/api/";h.defaults.baseURL=p;const f=async(t,r=1,o=15)=>(await h.get(p,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}})).data,y=t=>t.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:s,comments:a,downloads:b})=>`
    <li class="gallery-item">
      <a href="${o}" class="gallery-link">
        <img class="gallery-img" src="${r}" alt="${i}" width="360" height="200"/>
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${a}</p>
        <p><b>Downloads:</b> ${b}</p>
      </div>
    </li>
  `).join("");let u;const L=()=>{u?u.refresh():u=new F(".gallery a",{captionsData:"alt",captionDelay:250})},w={searchForm:document.querySelector(".search-form"),inputForm:document.querySelector(".form-input"),searchBtn:document.querySelector(".form-button"),gallery:document.querySelector(".gallery"),loaderEl:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},{searchForm:A,inputForm:x,searchBtn:B,gallery:l,loaderEl:d,loadMoreBtn:m}=w;let c="",g=1;A.addEventListener("submit",E);m.addEventListener("click",q);async function E(t){if(t.preventDefault(),c=t.target.elements.search.value.trim(),c===""){l.innerHTML="",t.target.reset(),n.show({message:"Input field cannot be empty",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"});return}l.innerHTML="",g=1,m.classList.add("is-hidden"),d.classList.remove("is-hidden");try{const r=await f(c,g);if(r.total===0){n.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"});return}l.innerHTML=y(r.hits),L(),t.target.reset(),r.hits.length===15&&m.classList.remove("is-hidden")}catch(r){console.log(r),n.show({message:"An error occurred while fetching images. Please try again.",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"})}finally{d.classList.add("is-hidden")}}async function q(){g+=1,d.classList.remove("is-hidden");try{const t=await f(c,g);l.innerHTML+=y(t.hits),L(),t.hits.length<15&&m.classList.add("is-hidden")}catch(t){console.log(t),n.show({message:"An error occurred while fetching images. Please try again.",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"})}finally{d.classList.add("is-hidden")}}
//# sourceMappingURL=commonHelpers.js.map
