import{a as p,S,i as r}from"./assets/vendor-b11e2a50.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const w="44009462-82273816cd5912ea13bf70156",f="https://pixabay.com/api/";p.defaults.baseURL=f;const y=async(t,s=1,i=15)=>(await p.get(f,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:i}})).data,b=t=>t.map(({webformatURL:s,largeImageURL:i,tags:a,likes:e,views:o,comments:n,downloads:L})=>`
    <li class="gallery-item">
      <a href="${i}" class="gallery-link">
        <img class="gallery-img" src="${s}" alt="${a}" width="360" height="200"/>
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${o}</p>
        <p><b>Comments:</b> ${n}</p>
        <p><b>Downloads:</b> ${L}</p>
      </div>
    </li>
  `).join("");let u;const F=()=>{u?u.refresh():u=new S(".gallery a",{captionsData:"alt",captionDelay:250})},A={searchForm:document.querySelector(".search-form"),inputForm:document.querySelector(".form-input"),searchBtn:document.querySelector(".form-button"),gallery:document.querySelector(".gallery"),loaderEl:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")},{searchForm:C,inputForm:v,searchBtn:x,gallery:l,loaderEl:g,loadMoreBtn:m}=A;let c="",d=1,h=0;C.addEventListener("submit",E);m.addEventListener("click",B);async function E(t){if(t.preventDefault(),c=t.target.elements.search.value.trim(),c===""){l.innerHTML="",t.target.reset(),r.show({message:"Input field cannot be empty",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"});return}l.innerHTML="",d=1,m.classList.add("is-hidden"),g.classList.remove("is-hidden");try{const s=await y(c,d);if(h=s.totalHits,h===0){r.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"});return}l.innerHTML=b(s.hits),F(),t.target.reset(),s.hits.length<15?r.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"info"}):m.classList.remove("is-hidden")}catch(s){console.log(s),r.show({message:"An error occurred while fetching images. Please try again.",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"})}finally{g.classList.add("is-hidden")}}async function B(){d+=1,g.classList.remove("is-hidden");try{const t=await y(c,d);l.innerHTML+=b(t.hits),F(),H(),l.children.length>=h&&(m.classList.add("is-hidden"),r.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"info"}))}catch(t){console.log(t),r.show({message:"An error occurred while fetching images. Please try again.",position:"topRight",timeout:2e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",messageSize:"16px",messageLineHeight:"1.5",class:"error"})}finally{g.classList.add("is-hidden")}}function H(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
